/**
 *  Copyright 2017 Jeffrey Hoyt. Released under the terms of the MIT license.
 */

package io.github.tejedu.manhunt;

import org.bukkit.Material;
import java.util.List;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

public class Prizes
{
    public static List<Material> overworldPrizes = (List<Material>)Arrays.asList(
        Material.ACACIA_DOOR_ITEM,
        Material.ACACIA_FENCE_GATE,
        Material.ACACIA_FENCE,
        Material.ACACIA_STAIRS,
        Material.ACTIVATOR_RAIL,
        Material.ANVIL,
        Material.APPLE,
        Material.ARMOR_STAND,
        Material.ARROW,
        Material.BAKED_POTATO,
        Material.BANNER,
        Material.BED,
        Material.BEETROOT_SEEDS,
        Material.BEETROOT_SOUP,
        Material.BEETROOT,
        Material.BIRCH_DOOR_ITEM,
        Material.BIRCH_FENCE_GATE,
        Material.BIRCH_FENCE,
        Material.BIRCH_WOOD_STAIRS,
        Material.BLACK_GLAZED_TERRACOTTA,
        Material.BLUE_GLAZED_TERRACOTTA,
        Material.BOAT_ACACIA,
        Material.BOAT_BIRCH,
        Material.BOAT_DARK_OAK,
        Material.BOAT_JUNGLE,
        Material.BOAT_SPRUCE,
        Material.BOAT,
        Material.BONE_BLOCK,
        Material.BONE,
        Material.BOOK_AND_QUILL,
        Material.BOOK,
        Material.BOOKSHELF,
        Material.BOW,
        Material.BOWL,
        Material.BREAD,
        Material.BRICK_STAIRS,
        Material.BRICK,
        Material.BROWN_GLAZED_TERRACOTTA,
        Material.BROWN_MUSHROOM,
        Material.BUCKET,
        Material.CACTUS,
        Material.CAKE,
        Material.CARPET,
        Material.CARROT_ITEM,
        Material.CARROT_STICK,
        Material.CAULDRON_ITEM,
        Material.CHAINMAIL_BOOTS,
        Material.CHAINMAIL_CHESTPLATE,
        Material.CHAINMAIL_HELMET,
        Material.CHAINMAIL_LEGGINGS,
        Material.CHEST,
        Material.CLAY_BALL,
        Material.CLAY_BRICK,
        Material.CLAY,
        Material.COAL_BLOCK,
        Material.COAL_ORE,
        Material.COAL,
        Material.COBBLE_WALL,
        Material.COBBLESTONE_STAIRS,
        Material.COBBLESTONE,
        Material.COMPASS,
        Material.CONCRETE_POWDER,
        Material.CONCRETE,
        Material.COOKED_BEEF,
        Material.COOKED_CHICKEN,
        Material.COOKED_FISH,
        Material.COOKED_MUTTON,
        Material.COOKED_RABBIT,
        Material.COOKIE,
        Material.CYAN_GLAZED_TERRACOTTA,
        Material.DARK_OAK_DOOR_ITEM,
        Material.DARK_OAK_FENCE_GATE,
        Material.DARK_OAK_FENCE,
        Material.DARK_OAK_STAIRS,
        Material.DAYLIGHT_DETECTOR,
        Material.DEAD_BUSH,
        Material.DETECTOR_RAIL,
        Material.DIAMOND_AXE,
        Material.DIAMOND_BARDING,
        Material.DIAMOND_BLOCK,
        Material.DIAMOND_BOOTS,
        Material.DIAMOND_CHESTPLATE,
        Material.DIAMOND_HELMET,
        Material.DIAMOND_HOE,
        Material.DIAMOND_LEGGINGS,
        Material.DIAMOND_ORE,
        Material.DIAMOND_PICKAXE,
        Material.DIAMOND_SPADE,
        Material.DIAMOND_SWORD,
        Material.DIAMOND,
        Material.DIODE,
        Material.DIRT,
        Material.DISPENSER,
        Material.DOUBLE_PLANT,
        Material.DROPPER,
        Material.EGG,
        Material.EMERALD_BLOCK,
        Material.EMERALD_ORE,
        Material.EMERALD,
        Material.EMPTY_MAP,
        Material.ENCHANTMENT_TABLE,
        Material.ENDER_PEARL,
        Material.EXP_BOTTLE,
        Material.EXPLOSIVE_MINECART,
        Material.EYE_OF_ENDER,
        Material.FEATHER,
        Material.FENCE_GATE,
        Material.FENCE,
        Material.FERMENTED_SPIDER_EYE,
        Material.FIREBALL,
        Material.FIREWORK_CHARGE,
        Material.FIREWORK,
        Material.FISHING_ROD,
        Material.FLINT_AND_STEEL,
        Material.FLINT,
        Material.FLOWER_POT_ITEM,
        Material.FURNACE,
        Material.GLASS_BOTTLE,
        Material.GLASS,
        Material.GLOWSTONE_DUST,
        Material.GOLD_AXE,
        Material.GOLD_BARDING,
        Material.GOLD_BLOCK,
        Material.GOLD_BOOTS,
        Material.GOLD_CHESTPLATE,
        Material.GOLD_HELMET,
        Material.GOLD_HOE,
        Material.GOLD_INGOT,
        Material.GOLD_LEGGINGS,
        Material.GOLD_NUGGET,
        Material.GOLD_ORE,
        Material.GOLD_PICKAXE,
        Material.GOLD_PLATE,
        Material.GOLD_RECORD,
        Material.GOLD_SPADE,
        Material.GOLD_SWORD,
        Material.GOLDEN_APPLE,
        Material.GOLDEN_CARROT,
        Material.GRASS_PATH,
        Material.GRASS,
        Material.GRAVEL,
        Material.GRAY_GLAZED_TERRACOTTA,
        Material.GREEN_GLAZED_TERRACOTTA,
        Material.GREEN_RECORD,
        Material.GRILLED_PORK,
        Material.HARD_CLAY,
        Material.HAY_BLOCK,
        Material.HOPPER_MINECART,
        Material.HOPPER,
        Material.HUGE_MUSHROOM_1,
        Material.HUGE_MUSHROOM_2,
        Material.ICE,
        Material.INK_SACK,
        Material.IRON_AXE,
        Material.IRON_BARDING,
        Material.IRON_BLOCK,
        Material.IRON_BOOTS,
        Material.IRON_CHESTPLATE,
        Material.IRON_DOOR,
        Material.IRON_FENCE,
        Material.IRON_HELMET,
        Material.IRON_HOE,
        Material.IRON_INGOT,
        Material.IRON_LEGGINGS,
        Material.IRON_NUGGET,
        Material.IRON_ORE,
        Material.IRON_PICKAXE,
        Material.IRON_PLATE,
        Material.IRON_SPADE,
        Material.IRON_SWORD,
        Material.IRON_TRAPDOOR,
        Material.ITEM_FRAME,
        Material.JACK_O_LANTERN,
        Material.JUKEBOX,
        Material.JUNGLE_DOOR_ITEM,
        Material.JUNGLE_FENCE_GATE,
        Material.JUNGLE_FENCE,
        Material.JUNGLE_WOOD_STAIRS,
        Material.LADDER,
        Material.LAPIS_BLOCK,
        Material.LAPIS_ORE,
        Material.LAVA_BUCKET,
        Material.LEASH,
        Material.LEATHER_BOOTS,
        Material.LEATHER_CHESTPLATE,
        Material.LEATHER_HELMET,
        Material.LEATHER_LEGGINGS,
        Material.LEATHER,
        Material.LEAVES_2,
        Material.LEAVES,
        Material.LEVER,
        Material.LIGHT_BLUE_GLAZED_TERRACOTTA,
        Material.LIME_GLAZED_TERRACOTTA,
        Material.LOG_2,
        Material.LOG,
        Material.LONG_GRASS,
        Material.MAGENTA_GLAZED_TERRACOTTA,
        Material.MAP,
        Material.MELON_BLOCK,
        Material.MELON_SEEDS,
        Material.MELON,
        Material.MILK_BUCKET,
        Material.MINECART,
        Material.MOSSY_COBBLESTONE,
        Material.MUSHROOM_SOUP,
        Material.MUTTON,
        Material.MYCEL,
        Material.NAME_TAG,
        Material.NOTE_BLOCK,
        Material.OBSIDIAN,
        Material.ORANGE_GLAZED_TERRACOTTA,
        Material.PACKED_ICE,
        Material.PAINTING,
        Material.PAPER,
        Material.PINK_GLAZED_TERRACOTTA,
        Material.PISTON_BASE,
        Material.PISTON_STICKY_BASE,
        Material.POISONOUS_POTATO,
        Material.PORK,
        Material.POTATO_ITEM,
        Material.POWERED_MINECART,
        Material.POWERED_RAIL,
        Material.PRISMARINE_CRYSTALS,
        Material.PRISMARINE_SHARD,
        Material.PRISMARINE,
        Material.PUMPKIN_PIE,
        Material.PUMPKIN_SEEDS,
        Material.PUMPKIN,
        Material.PURPLE_GLAZED_TERRACOTTA,
        Material.RABBIT_FOOT,
        Material.RABBIT_HIDE,
        Material.RABBIT_STEW,
        Material.RABBIT,
        Material.RAILS,
        Material.RAW_BEEF,
        Material.RAW_CHICKEN,
        Material.RAW_FISH,
        Material.RECORD_10,
        Material.RECORD_11,
        Material.RECORD_12,
        Material.RECORD_3,
        Material.RECORD_4,
        Material.RECORD_5,
        Material.RECORD_6,
        Material.RECORD_7,
        Material.RECORD_8,
        Material.RECORD_9,
        Material.RED_GLAZED_TERRACOTTA,
        Material.RED_MUSHROOM,
        Material.RED_ROSE,
        Material.RED_SANDSTONE_STAIRS,
        Material.RED_SANDSTONE,
        Material.REDSTONE_BLOCK,
        Material.REDSTONE_COMPARATOR,
        Material.REDSTONE_LAMP_OFF,
        Material.REDSTONE_ORE,
        Material.REDSTONE_TORCH_ON,
        Material.REDSTONE,
        Material.ROTTEN_FLESH,
        Material.SADDLE,
        Material.SAND,
        Material.SANDSTONE_STAIRS,
        Material.SANDSTONE,
        Material.SAPLING,
        Material.SEA_LANTERN,
        Material.SEEDS,
        Material.SHEARS,
        Material.SHIELD,
        Material.SIGN,
        Material.SILVER_GLAZED_TERRACOTTA,
        Material.SKULL_ITEM,
        Material.SLIME_BALL,
        Material.SLIME_BLOCK,
        Material.SMOOTH_BRICK,
        Material.SMOOTH_STAIRS,
        Material.SNOW_BALL,
        Material.SNOW_BLOCK,
        Material.SNOW,
        Material.SOIL,
        Material.SPECKLED_MELON,
        Material.SPIDER_EYE,
        Material.SPLASH_POTION,
        Material.SPONGE,
        Material.SPRUCE_DOOR_ITEM,
        Material.SPRUCE_FENCE_GATE,
        Material.SPRUCE_FENCE,
        Material.SPRUCE_WOOD_STAIRS,
        Material.STAINED_CLAY,
        Material.STAINED_GLASS_PANE,
        Material.STAINED_GLASS,
        Material.STEP,
        Material.STICK,
        Material.STONE_AXE,
        Material.STONE_BUTTON,
        Material.STONE_HOE,
        Material.STONE_PICKAXE,
        Material.STONE_PLATE,
        Material.STONE_SLAB2,
        Material.STONE_SPADE,
        Material.STONE_SWORD,
        Material.STONE,
        Material.STORAGE_MINECART,
        Material.STRING,
        Material.SUGAR_CANE,
        Material.SUGAR,
        Material.SULPHUR,
        Material.THIN_GLASS,
        Material.TNT,
        Material.TORCH,
        Material.TOTEM,
        Material.TRAP_DOOR,
        Material.TRAPPED_CHEST,
        Material.TRIPWIRE_HOOK,
        Material.VINE,
        Material.WATCH,
        Material.WATER_BUCKET,
        Material.WATER_LILY,
        Material.WEB,
        Material.WHEAT,
        Material.WHITE_GLAZED_TERRACOTTA,
        Material.WOOD_AXE,
        Material.WOOD_BUTTON,
        Material.WOOD_DOOR,
        Material.WOOD_HOE,
        Material.WOOD_PICKAXE,
        Material.WOOD_PLATE,
        Material.WOOD_SPADE,
        Material.WOOD_STAIRS,
        Material.WOOD_STEP,
        Material.WOOD_SWORD,
        Material.WOOD,
        Material.WOOL,
        Material.WORKBENCH,
        Material.WRITTEN_BOOK,
        Material.YELLOW_FLOWER,
        Material.YELLOW_GLAZED_TERRACOTTA );

    public static List<Material> netherPrizes = (List<Material>)Arrays.asList(
        Material.BEACON,
        Material.BLAZE_POWDER,
        Material.BLAZE_ROD,
        Material.BREWING_STAND_ITEM,
        Material.ENDER_CHEST,
        Material.GLOWSTONE,
        Material.MAGMA_CREAM,
        Material.MAGMA,
        Material.NETHER_BRICK_ITEM,
        Material.NETHER_BRICK_STAIRS,
        Material.NETHER_BRICK,
        Material.NETHER_FENCE,
        Material.NETHER_STALK,
        Material.NETHER_STAR,
        Material.NETHER_WART_BLOCK,
        Material.NETHERRACK,
        Material.OBSERVER,
        Material.QUARTZ_BLOCK,
        Material.QUARTZ_ORE,
        Material.QUARTZ_STAIRS,
        Material.QUARTZ,
        Material.RED_NETHER_BRICK,
        Material.SOUL_SAND);

    public static List<Material> endPrizes = (List<Material>)Arrays.asList(
        Material.BLACK_SHULKER_BOX,
        Material.BLUE_SHULKER_BOX,
        Material.BROWN_SHULKER_BOX,
        Material.CHORUS_FLOWER,
        Material.CHORUS_FRUIT_POPPED,
        Material.CHORUS_FRUIT,
        Material.CHORUS_PLANT,
        Material.CYAN_SHULKER_BOX,
        Material.DRAGONS_BREATH,
        Material.ELYTRA,
        Material.END_BRICKS,
        Material.END_CRYSTAL,
        Material.END_ROD,
        Material.ENDER_STONE,
        Material.GRAY_SHULKER_BOX,
        Material.GREEN_SHULKER_BOX,
        Material.LIGHT_BLUE_SHULKER_BOX,
        Material.LIME_SHULKER_BOX,
        Material.MAGENTA_SHULKER_BOX,
        Material.ORANGE_SHULKER_BOX,
        Material.PINK_SHULKER_BOX,
        Material.PURPLE_SHULKER_BOX,
        Material.PURPUR_BLOCK,
        Material.PURPUR_PILLAR,
        Material.PURPUR_SLAB,
        Material.PURPUR_STAIRS,
        Material.RED_SHULKER_BOX,
        Material.SHULKER_SHELL,
        Material.SILVER_SHULKER_BOX,
        Material.WHITE_SHULKER_BOX,
        Material.YELLOW_SHULKER_BOX);

    public static List<Material> unusedPrizes = (List<Material>)Arrays.asList(
        Material.ACACIA_DOOR,
        Material.AIR,
        Material.BARRIER,
        Material.BED_BLOCK,
        Material.BEDROCK,
        Material.BEETROOT_BLOCK,
        Material.BIRCH_DOOR,
        Material.BREWING_STAND,
        Material.BURNING_FURNACE,
        Material.CAKE_BLOCK,
        Material.CARROT,
        Material.CAULDRON,
        Material.COCOA,
        Material.COMMAND_CHAIN,
        Material.COMMAND_MINECART,
        Material.COMMAND_REPEATING,
        Material.COMMAND,
        Material.CROPS,
        Material.DARK_OAK_DOOR,
        Material.DAYLIGHT_DETECTOR_INVERTED,
        Material.DIODE_BLOCK_OFF,
        Material.DIODE_BLOCK_ON,
        Material.DOUBLE_STEP,
        Material.DOUBLE_STONE_SLAB2,
        Material.DRAGON_EGG,
        Material.ENCHANTED_BOOK,
        Material.END_GATEWAY,
        Material.ENDER_PORTAL_FRAME,
        Material.ENDER_PORTAL,
        Material.FIRE,
        Material.FLOWER_POT,
        Material.FROSTED_ICE,
        Material.GLOWING_REDSTONE_ORE,
        Material.IRON_DOOR_BLOCK,
        Material.JUNGLE_DOOR,
        Material.KNOWLEDGE_BOOK,
        Material.LAVA,
        Material.LINGERING_POTION,
        Material.MELON_STEM,
        Material.MOB_SPAWNER,
        Material.MONSTER_EGG,
        Material.MONSTER_EGGS, //silverfish stone block
        Material.NETHER_WARTS,
        Material.PISTON_EXTENSION,
        Material.PISTON_MOVING_PIECE,
        Material.PORTAL,
        Material.POTATO,
        Material.POTION,
        Material.PUMPKIN_STEM,
        Material.PURPUR_DOUBLE_SLAB,
        Material.REDSTONE_COMPARATOR_OFF,
        Material.REDSTONE_COMPARATOR_ON,
        Material.REDSTONE_LAMP_ON,
        Material.REDSTONE_TORCH_OFF,
        Material.REDSTONE_WIRE,
        Material.SIGN_POST,
        Material.SKULL,
        Material.SPECTRAL_ARROW,
        Material.SPRUCE_DOOR,
        Material.STANDING_BANNER,
        Material.STATIONARY_LAVA,
        Material.STATIONARY_WATER,
        Material.STRUCTURE_BLOCK,
        Material.STRUCTURE_VOID,
        Material.SUGAR_CANE_BLOCK,
        Material.TIPPED_ARROW,
        Material.TRIPWIRE,
        Material.WALL_BANNER,
        Material.WALL_SIGN,
        Material.WATER,
        Material.WOOD_DOUBLE_STEP,
        Material.WOODEN_DOOR);

    public static Material[] enchantableList = {
        Material.DIAMOND_AXE,
        Material.DIAMOND_BOOTS,
        Material.DIAMOND_CHESTPLATE,
        Material.DIAMOND_HELMET,
        Material.DIAMOND_LEGGINGS,
        Material.DIAMOND_PICKAXE,
        Material.DIAMOND_SPADE,
        Material.DIAMOND_SWORD,
        Material.GOLD_AXE,
        Material.GOLD_BOOTS,
        Material.GOLD_CHESTPLATE,
        Material.GOLD_HELMET,
        Material.GOLD_LEGGINGS,
        Material.GOLD_PICKAXE,
        Material.GOLD_SPADE,
        Material.GOLD_SWORD,
        Material.IRON_AXE,
        Material.IRON_BOOTS,
        Material.IRON_CHESTPLATE,
        Material.IRON_HELMET,
        Material.IRON_LEGGINGS,
        Material.IRON_PICKAXE,
        Material.IRON_SPADE,
        Material.IRON_SWORD,
        Material.LEATHER_BOOTS,
        Material.LEATHER_CHESTPLATE,
        Material.LEATHER_HELMET,
        Material.LEATHER_LEGGINGS,
        Material.STONE_AXE,
        Material.STONE_PICKAXE,
        Material.STONE_SPADE,
        Material.STONE_SWORD,
        Material.WOOD_AXE,
        Material.WOOD_PICKAXE,
        Material.WOOD_SPADE,
        Material.WOOD_SWORD,
    };

    public static Map<Material, Integer> prizeLimits = new HashMap<Material, Integer>();

    public static void setPrizeLimits() {
        prizeLimits.put(Material.NETHER_STAR, 3);
        prizeLimits.put(Material.BEACON, 3);
        prizeLimits.put(Material.END_CRYSTAL, 3);
        prizeLimits.put(Material.SKULL_ITEM, 5);
        prizeLimits.put(Material.IRON_BLOCK, 32);
        prizeLimits.put(Material.GOLD_BLOCK, 16);
        prizeLimits.put(Material.DIAMOND_BLOCK, 8);
        prizeLimits.put(Material.EMERALD_BLOCK, 8);
        prizeLimits.put(Material.DIAMOND, 32);
        prizeLimits.put(Material.DIAMOND_ORE, 16);
        prizeLimits.put(Material.GOLDEN_APPLE, 5);
        prizeLimits.put(Material.ENDER_CHEST, 8);
        prizeLimits.put(Material.GHAST_TEAR, 8);
        prizeLimits.put(Material.AIR, 1);
    }
}

/* old prize List

Material[] materialList = { Material.STONE, Material.GRASS, Material.DIRT, Material.COBBLESTONE, Material.WOOD,
                Material.SAPLING, Material.SAND, Material.GRAVEL, Material.GOLD_ORE, Material.IRON_ORE,
                Material.COAL_ORE, Material.LOG, Material.LEAVES, Material.SPONGE, Material.GLASS, Material.LAPIS_ORE,
                Material.LAPIS_BLOCK, Material.DISPENSER, Material.SANDSTONE, Material.NOTE_BLOCK,
                Material.POWERED_RAIL, Material.DETECTOR_RAIL, Material.WEB, Material.LONG_GRASS, Material.DEAD_BUSH,
                Material.WOOL, Material.YELLOW_FLOWER, Material.RED_ROSE, Material.BROWN_MUSHROOM,
                Material.RED_MUSHROOM, Material.GOLD_BLOCK, Material.IRON_BLOCK, Material.BRICK, Material.TNT,
                Material.BOOKSHELF, Material.MOSSY_COBBLESTONE, Material.OBSIDIAN, Material.TORCH, Material.WOOD_STAIRS,
                Material.CHEST, Material.DIAMOND_ORE, Material.WORKBENCH, Material.CROPS, Material.FURNACE,
                Material.WOODEN_DOOR, Material.LADDER, Material.COBBLESTONE_STAIRS, Material.LEVER,
                Material.REDSTONE_ORE, Material.STONE_BUTTON, Material.SNOW, Material.ICE, Material.CACTUS,
                Material.CLAY, Material.JUKEBOX, Material.FENCE, Material.PUMPKIN, Material.NETHERRACK,
                Material.SOUL_SAND, Material.GLOWSTONE, Material.JACK_O_LANTERN, Material.STAINED_GLASS,
                Material.TRAP_DOOR, Material.IRON_FENCE, Material.THIN_GLASS, Material.MELON_BLOCK, Material.VINE,
                Material.FENCE_GATE, Material.BRICK_STAIRS, Material.SMOOTH_STAIRS, Material.WATER_LILY,
                Material.NETHER_BRICK, Material.NETHER_FENCE, Material.NETHER_BRICK_STAIRS, Material.NETHER_WARTS,
                Material.ENCHANTMENT_TABLE, Material.BREWING_STAND, Material.CAULDRON, Material.ENDER_STONE,
                Material.REDSTONE_LAMP_OFF, Material.COCOA, Material.SANDSTONE_STAIRS, Material.EMERALD_ORE,
                Material.ENDER_CHEST, Material.TRIPWIRE_HOOK, Material.EMERALD_BLOCK, Material.SPRUCE_WOOD_STAIRS,
                Material.BIRCH_WOOD_STAIRS, Material.JUNGLE_WOOD_STAIRS, Material.BEACON, Material.COBBLE_WALL,
                Material.FLOWER_POT, Material.CARROT, Material.POTATO, Material.WOOD_BUTTON, Material.SKULL,
                Material.ANVIL, Material.TRAPPED_CHEST, Material.DAYLIGHT_DETECTOR, Material.REDSTONE_BLOCK,
                Material.QUARTZ_ORE, Material.HOPPER, Material.QUARTZ_BLOCK, Material.QUARTZ_STAIRS,
                Material.ACTIVATOR_RAIL, Material.DROPPER, Material.STAINED_CLAY, Material.STAINED_GLASS_PANE,
                Material.ACACIA_STAIRS, Material.DARK_OAK_STAIRS, Material.SLIME_BLOCK, Material.IRON_TRAPDOOR,
                Material.PRISMARINE, Material.SEA_LANTERN, Material.HAY_BLOCK, Material.CARPET, Material.HARD_CLAY,
                Material.COAL_BLOCK, Material.PACKED_ICE, Material.RED_SANDSTONE, Material.RED_SANDSTONE_STAIRS,
                Material.SPRUCE_FENCE_GATE, Material.BIRCH_FENCE_GATE, Material.JUNGLE_FENCE_GATE,
                Material.DARK_OAK_FENCE_GATE, Material.ACACIA_FENCE_GATE, Material.SPRUCE_FENCE, Material.BIRCH_FENCE,
                Material.JUNGLE_FENCE, Material.DARK_OAK_FENCE, Material.ACACIA_FENCE, Material.SPRUCE_DOOR,
                Material.BIRCH_DOOR, Material.JUNGLE_DOOR, Material.ACACIA_DOOR, Material.DARK_OAK_DOOR,
                Material.IRON_SPADE, Material.IRON_PICKAXE, Material.IRON_AXE, Material.FLINT_AND_STEEL, Material.APPLE,
                Material.BOW, Material.ARROW, Material.COAL, Material.DIAMOND, Material.IRON_INGOT, Material.GOLD_INGOT,
                Material.IRON_SWORD, Material.WOOD_SWORD, Material.WOOD_SPADE, Material.WOOD_PICKAXE, Material.WOOD_AXE,
                Material.STONE_SWORD, Material.STONE_SPADE, Material.STONE_PICKAXE, Material.STONE_AXE,
                Material.DIAMOND_SWORD, Material.DIAMOND_SPADE, Material.DIAMOND_PICKAXE, Material.DIAMOND_AXE,
                Material.STICK, Material.BOWL, Material.MUSHROOM_SOUP, Material.GOLD_SWORD, Material.GOLD_SPADE,
                Material.GOLD_PICKAXE, Material.GOLD_AXE, Material.STRING, Material.FEATHER, Material.SULPHUR,
                Material.WOOD_HOE, Material.STONE_HOE, Material.IRON_HOE, Material.DIAMOND_HOE, Material.GOLD_HOE,
                Material.SEEDS, Material.WHEAT, Material.BREAD, Material.LEATHER_HELMET, Material.LEATHER_CHESTPLATE,
                Material.LEATHER_LEGGINGS, Material.LEATHER_BOOTS, Material.CHAINMAIL_HELMET,
                Material.CHAINMAIL_CHESTPLATE, Material.CHAINMAIL_LEGGINGS, Material.CHAINMAIL_BOOTS,
                Material.IRON_HELMET, Material.IRON_CHESTPLATE, Material.IRON_LEGGINGS, Material.IRON_BOOTS,
                Material.DIAMOND_HELMET, Material.DIAMOND_CHESTPLATE, Material.DIAMOND_LEGGINGS, Material.DIAMOND_BOOTS,
                Material.GOLD_HELMET, Material.GOLD_CHESTPLATE, Material.GOLD_LEGGINGS, Material.GOLD_BOOTS,
                Material.FLINT, Material.PORK, Material.GRILLED_PORK, Material.PAINTING, Material.GOLDEN_APPLE,
                Material.SIGN, Material.WOOD_DOOR, Material.BUCKET, Material.WATER_BUCKET, Material.LAVA_BUCKET,
                Material.MINECART, Material.SADDLE, Material.IRON_DOOR, Material.REDSTONE, Material.SNOW_BALL,
                Material.BOAT, Material.LEATHER, Material.MILK_BUCKET, Material.CLAY_BRICK, Material.CLAY_BALL,
                Material.SUGAR_CANE, Material.PAPER, Material.BOOK, Material.SLIME_BALL, Material.STORAGE_MINECART,
                Material.POWERED_MINECART, Material.EGG, Material.COMPASS, Material.FISHING_ROD, Material.WATCH,
                Material.GLOWSTONE_DUST, Material.RAW_FISH, Material.COOKED_FISH, Material.INK_SACK, Material.BONE,
                Material.SUGAR, Material.CAKE, Material.BED, Material.DIODE, Material.COOKIE, Material.MAP,
                Material.SHEARS, Material.MELON, Material.PUMPKIN_SEEDS, Material.MELON_SEEDS, Material.RAW_BEEF,
                Material.COOKED_BEEF, Material.RAW_CHICKEN, Material.COOKED_CHICKEN, Material.ROTTEN_FLESH,
                Material.ENDER_PEARL, Material.BLAZE_ROD, Material.GHAST_TEAR, Material.GOLD_NUGGET,
                Material.NETHER_STALK, Material.POTION, Material.GLASS_BOTTLE, Material.SPIDER_EYE,
                Material.FERMENTED_SPIDER_EYE, Material.BLAZE_POWDER, Material.MAGMA_CREAM, Material.BREWING_STAND_ITEM,
                Material.CAULDRON_ITEM, Material.EYE_OF_ENDER, Material.SPECKLED_MELON, Material.MONSTER_EGG,
                Material.EXP_BOTTLE, Material.FIREBALL, Material.BOOK_AND_QUILL, Material.WRITTEN_BOOK,
                Material.EMERALD, Material.ITEM_FRAME, Material.FLOWER_POT_ITEM, Material.CARROT_ITEM,
                Material.POTATO_ITEM, Material.BAKED_POTATO, Material.POISONOUS_POTATO, Material.EMPTY_MAP,
                Material.GOLDEN_CARROT, Material.SKULL_ITEM, Material.CARROT_STICK, Material.NETHER_STAR,
                Material.PUMPKIN_PIE, Material.FIREWORK, Material.FIREWORK_CHARGE, Material.ENCHANTED_BOOK,
                Material.REDSTONE_COMPARATOR, Material.NETHER_BRICK_ITEM, Material.QUARTZ, Material.EXPLOSIVE_MINECART,
                Material.HOPPER_MINECART, Material.PRISMARINE_SHARD, Material.PRISMARINE_CRYSTALS, Material.RABBIT,
                Material.COOKED_RABBIT, Material.RABBIT_STEW, Material.RABBIT_FOOT, Material.RABBIT_HIDE,
                Material.ARMOR_STAND, Material.IRON_BARDING, Material.GOLD_BARDING, Material.DIAMOND_BARDING,
                Material.LEASH, Material.NAME_TAG, Material.COMMAND_MINECART, Material.MUTTON, Material.COOKED_MUTTON,
                Material.BANNER, Material.SPRUCE_DOOR_ITEM, Material.BIRCH_DOOR_ITEM, Material.JUNGLE_DOOR_ITEM,
                Material.ACACIA_DOOR_ITEM, Material.DARK_OAK_DOOR_ITEM, Material.GOLD_RECORD, Material.GREEN_RECORD,
                Material.RECORD_3, Material.RECORD_4, Material.RECORD_5, Material.RECORD_6, Material.RECORD_7,
                Material.RECORD_8, Material.RECORD_9, Material.RECORD_10, Material.RECORD_11, Material.RECORD_12 };
*/
