/**
 *  Copyright 2017 Jeffrey Hoyt. Released under the terms of the MIT license.
 */

package io.github.tejedu.manhunt;

import org.bukkit.Material;
import java.util.List;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

public class Prizes
{
    public static List<Material> overworldPrizes = (List<Material>)Arrays.asList(
        // Material.ACACIA_SAPLING,
        // Material.ACTIVATOR_RAIL,
        // Material.ALLIUM,
        // Material.ANVIL,
        // Material.APPLE,
        // Material.AZURE_BLUET,
        // Material.BAKED_POTATO,
        // Material.BAMBOO,
        // Material.BARREL,
        // Material.BEE_NEST,
        // Material.BEEHIVE,
        // Material.BEETROOT_SEEDS,
        // Material.BEETROOT,
        // Material.BELL,
        // Material.BIRCH_SAPLING,
        // Material.BLAST_FURNACE,
        // Material.BLUE_ICE,
        // Material.BLUE_ORCHID,
        // Material.BONE_BLOCK,
        // Material.BOOK,
        // Material.BOOKSHELF,
        // Material.BRAIN_CORAL_BLOCK,
        // Material.BRAIN_CORAL_FAN,
        // Material.BRAIN_CORAL,
        // Material.BRICK_SLAB,
        // Material.BRICK_STAIRS,
        // Material.BRICK,
        // Material.BRICKS,
        // Material.BUBBLE_CORAL_BLOCK,
        // Material.BUBBLE_CORAL_FAN,
        // Material.BUBBLE_CORAL,
        // Material.CACTUS,
        // Material.CAKE,
        // Material.CAMPFIRE,
        // Material.CARROT_ON_A_STICK,
        // Material.CARROT,
        // Material.CARTOGRAPHY_TABLE,
        // Material.CARVED_PUMPKIN,
        // Material.CAULDRON,
        // Material.CHAINMAIL_BOOTS,
        // Material.CHAINMAIL_CHESTPLATE,
        // Material.CHAINMAIL_HELMET,
        // Material.CHAINMAIL_LEGGINGS,
        // Material.CHARCOAL,
        // Material.CHEST_MINECART,
        // Material.CHISELED_QUARTZ_BLOCK,
        // Material.CHISELED_RED_SANDSTONE,
        // Material.CHISELED_SANDSTONE,
        // Material.CHISELED_STONE_BRICKS,
        // Material.CLAY_BALL,
        // Material.CLAY,
        // Material.CLOCK,
        // Material.COAL_BLOCK,
        // Material.COAL_ORE,
        // Material.COAL,
        // Material.COBWEB,
        // Material.COCOA_BEANS,
        // Material.COD_BUCKET,
        Material.COMPASS,
        // Material.COMPOSTER,
        // Material.CONDUIT,
        // Material.CORNFLOWER,
        // Material.CRACKED_STONE_BRICKS,
        Material.CREEPER_HEAD,
        // Material.CROSSBOW,
        Material.CUT_RED_SANDSTONE,
        // Material.CUT_SANDSTONE,
        Material.CYAN_WOOL,
        // Material.DANDELION,
        // Material.DARK_OAK_SAPLING,
        Material.DARK_PRISMARINE_SLAB,
        Material.DARK_PRISMARINE_STAIRS,
        Material.DARK_PRISMARINE,
        // Material.DETECTOR_RAIL,
        // Material.DIAMOND_AXE,
        // Material.DIAMOND_BLOCK,
        // Material.DIAMOND_BOOTS,
        // Material.DIAMOND_CHESTPLATE,
        // Material.DIAMOND_HELMET,
        // Material.DIAMOND_HOE,
        // Material.DIAMOND_HORSE_ARMOR,
        // Material.DIAMOND_LEGGINGS,
        // Material.DIAMOND_ORE,
        // Material.DIAMOND_PICKAXE,
        // Material.DIAMOND_SHOVEL,
        // Material.DIAMOND_SWORD,
        Material.DIAMOND,
        // Material.DISPENSER,
        // Material.DRIED_KELP_BLOCK,
        // Material.DRIED_KELP,
        // Material.DROPPER,
        Material.EGG,
        // Material.EMERALD_BLOCK,
        // Material.EMERALD_ORE,
        Material.EMERALD,
        // Material.ENCHANTED_GOLDEN_APPLE,
        // Material.ENCHANTING_TABLE,
        Material.ENDER_PEARL,
        Material.EXPERIENCE_BOTTLE,
        // Material.FERMENTED_SPIDER_EYE,
        // Material.FERN,
        Material.FIRE_CHARGE,
        // Material.FIRE_CORAL_BLOCK,
        // Material.FIRE_CORAL_FAN,
        // Material.FIRE_CORAL,
        Material.FIREWORK_ROCKET,
        Material.FIREWORK_STAR,
        // Material.FISHING_ROD,
        Material.FLETCHING_TABLE,
        // Material.FLINT_AND_STEEL,
        // Material.FLOWER_POT,
        // Material.GLASS_PANE,
        // Material.GLASS,
        Material.GLISTERING_MELON_SLICE,
        // Material.GLOWSTONE_DUST,
        // Material.GOLD_BLOCK,
        // Material.GOLD_INGOT,
        // Material.GOLD_NUGGET,
        Material.GOLD_ORE,
        // Material.HAY_BLOCK,
        // Material.HEART_OF_THE_SEA,
        // Material.HEAVY_WEIGHTED_PRESSURE_PLATE,
        Material.HONEYCOMB,
        // Material.HONEYCOMB_BLOCK,
        // Material.HONEY_BLOCK,
        Material.HONEY_BOTTLE,
        // Material.HOPPER_MINECART,
        // Material.HOPPER,
        // Material.HORN_CORAL_BLOCK,
        // Material.HORN_CORAL_FAN,
        // Material.HORN_CORAL,
        // Material.ICE,
        // Material.INK_SAC,
        Material.IRON_BARS,
        Material.IRON_BLOCK,
        // Material.IRON_DOOR,
        // Material.IRON_HORSE_ARMOR,
        // Material.IRON_INGOT,
        // Material.IRON_NUGGET,
        // Material.IRON_ORE,
        // Material.IRON_TRAPDOOR,
        // Material.ITEM_FRAME,
        // Material.JACK_O_LANTERN,
        // Material.JUKEBOX,
        // Material.JUNGLE_SAPLING,
        // Material.KELP,
        Material.LANTERN,
        // Material.LAPIS_BLOCK,
        Material.LAPIS_LAZULI,
        // Material.LAPIS_ORE,
        // Material.LARGE_FERN,
        // Material.LAVA_BUCKET,
        Material.LEAD,
        // Material.LEATHER,
        Material.LECTERN,
        // Material.LIGHT_WEIGHTED_PRESSURE_PLATE,
        // Material.LILAC,
        // Material.LILY_OF_THE_VALLEY,
        // Material.LILY_PAD,
        Material.LOOM,
        // Material.MELON_SEEDS,
        // Material.MELON_SLICE,
        // Material.MELON,
        // Material.MILK_BUCKET,
        // Material.MINECART,
        // Material.MUSHROOM_STEW,
        Material.MUSIC_DISC_11,
        Material.MUSIC_DISC_13,
        Material.MUSIC_DISC_CAT,
        Material.MUSIC_DISC_CHIRP,
        Material.MUSIC_DISC_FAR,
        Material.MUSIC_DISC_MALL,
        Material.MUSIC_DISC_MELLOHI,
        Material.MUSIC_DISC_OTHERSIDE,
        Material.MUSIC_DISC_STAL,
        Material.MUSIC_DISC_STRAD,
        Material.MUSIC_DISC_WAIT,
        Material.MUSIC_DISC_WARD,
        // Material.MYCELIUM,
        // Material.NAME_TAG,
        // Material.NAUTILUS_SHELL,
        // Material.NOTE_BLOCK,
        // Material.OBSERVER,
        Material.OBSIDIAN,
        Material.OXEYE_DAISY,
        // Material.PACKED_ICE,
        // Material.PAINTING,
        // Material.PHANTOM_MEMBRANE,
        // Material.PISTON,
        // Material.PLAYER_HEAD,
        // Material.POPPY,
        Material.PORKCHOP,
        Material.POTATO,
        Material.POTION,
        Material.POTION,
        Material.POTION,
        Material.POTION,
        Material.POTION,
        Material.POTION,
        Material.POTION,
        Material.POTION,
        Material.POTION,
        Material.POTION,
        Material.POTION,
        Material.POTION,
        // Material.POWERED_RAIL,
        // Material.PRISMARINE_BRICK_SLAB,
        // Material.PRISMARINE_BRICK_STAIRS,
        // Material.PRISMARINE_BRICKS,
        // Material.PRISMARINE_CRYSTALS,
        // Material.PRISMARINE_SHARD,
        // Material.PRISMARINE_SLAB,
        // Material.PRISMARINE_STAIRS,
        // Material.PRISMARINE,
        Material.PUFFERFISH_BUCKET,
        // Material.PUMPKIN_PIE,
        // Material.PUMPKIN_SEEDS,
        // Material.PUMPKIN,
        // Material.RABBIT_FOOT,
        // Material.RABBIT_HIDE,
        Material.RABBIT_STEW,
        // Material.RAIL,
        // Material.RED_MUSHROOM,
        Material.RED_SAND,
        Material.RED_SANDSTONE_SLAB,
        Material.RED_SANDSTONE_STAIRS,
        Material.RED_SANDSTONE,
        // Material.RED_TULIP,
        Material.REDSTONE_BLOCK,
        Material.REDSTONE_LAMP,
        Material.REDSTONE_ORE,
        Material.REDSTONE_TORCH,
        Material.REDSTONE,
        Material.REPEATER,
        // Material.ROSE_BUSH,
        // Material.SADDLE,
        // Material.SALMON_BUCKET,
        // Material.SALMON,
        Material.SCAFFOLDING,
        // Material.SCUTE,
        Material.SEA_LANTERN,
        // Material.SEA_PICKLE,
        Material.SHIELD,
        Material.SKELETON_SKULL,
        // Material.SLIME_BALL,
        // Material.SLIME_BLOCK,
        Material.SMITHING_TABLE,
        Material.SMOKER,
        Material.SMOOTH_RED_SANDSTONE,
        // Material.SMOOTH_SANDSTONE,
        // Material.SMOOTH_STONE,
        // Material.SNOW_BLOCK,
        // Material.SNOW,
        // Material.SNOWBALL,
        // Material.SPECTRAL_ARROW,
        // Material.SPIDER_EYE,
        Material.SPLASH_POTION,
        Material.SPLASH_POTION,
        Material.SPLASH_POTION,
        Material.SPLASH_POTION,
        Material.SPLASH_POTION,
        Material.SPLASH_POTION,
        Material.SPLASH_POTION,
        Material.SPLASH_POTION,
        Material.SPLASH_POTION,
        Material.SPLASH_POTION,
        Material.SPLASH_POTION,
        Material.SPLASH_POTION,
        Material.SPLASH_POTION,
        Material.SPLASH_POTION,
        Material.SPLASH_POTION,
        Material.SPLASH_POTION,
        // Material.SPONGE,
        // Material.SPRUCE_SAPLING,
        // Material.STICKY_PISTON,
        // Material.STONECUTTER,
        Material.STRING,
        Material.SUGAR_CANE,
        // Material.SUNFLOWER,
        Material.SWEET_BERRIES,
        // Material.TALL_GRASS,
        // Material.TNT_MINECART,
        Material.TNT,
        // Material.TORCH,
        Material.TOTEM_OF_UNDYING,
        // Material.TRAPPED_CHEST,
        Material.TRIDENT,
        // Material.TRIPWIRE_HOOK,
        // Material.TROPICAL_FISH_BUCKET,
        Material.TUBE_CORAL_BLOCK,
        // Material.TUBE_CORAL_FAN,
        // Material.TUBE_CORAL,
        Material.TURTLE_EGG,
        Material.TURTLE_HELMET,
        // Material.VINE,
        // Material.WATER_BUCKET,
        Material.WET_SPONGE,
        // Material.WHEAT,
        Material.WITHER_ROSE,
        // Material.WRITABLE_BOOK,
        Material.ZOMBIE_HEAD,
        // 1.19
        Material.ACACIA_CHEST_BOAT,
        Material.BIRCH_CHEST_BOAT,
        Material.DARK_OAK_CHEST_BOAT,
        Material.DISC_FRAGMENT_5,
        Material.ECHO_SHARD,
        Material.FROGSPAWN,
        Material.GOAT_HORN,
        Material.JUNGLE_CHEST_BOAT,
        Material.MANGROVE_BOAT,
        Material.MANGROVE_PROPAGULE,
        Material.MANGROVE_ROOTS,
        Material.MUD,
        Material.MUD_BRICKS,
        Material.MUD_BRICK_SLAB,
        Material.MUD_BRICK_STAIRS,
        Material.MUD_BRICK_WALL,
        Material.MUDDY_MANGROVE_ROOTS,
        Material.MUSIC_DISC_5,
        Material.OAK_CHEST_BOAT,
        Material.OCHRE_FROGLIGHT,
        Material.PACKED_MUD,
        Material.PEARLESCENT_FROGLIGHT,
        Material.RECOVERY_COMPASS,
        Material.SCULK,
        Material.SCULK_CATALYST,
        //Material.SCULK_SHRIEKER,
        Material.SCULK_VEIN,
        Material.SPRUCE_CHEST_BOAT,
        Material.TADPOLE_BUCKET,
        Material.VERDANT_FROGLIGHT,
        //1.20
        Material.ACACIA_HANGING_SIGN,
        // Material.ACACIA_WALL_HANGING_SIGN,
        Material.ANGLER_POTTERY_SHERD,
        Material.ARCHER_POTTERY_SHERD,
        Material.ARMS_UP_POTTERY_SHERD,
        Material.BAMBOO_BLOCK,
        Material.BAMBOO_BUTTON,
        Material.BAMBOO_CHEST_RAFT,
        Material.BAMBOO_DOOR,
        Material.BAMBOO_FENCE_GATE,
        Material.BAMBOO_FENCE,
        Material.BAMBOO_HANGING_SIGN,
        Material.BAMBOO_MOSAIC_SLAB,
        Material.BAMBOO_MOSAIC_STAIRS,
        Material.BAMBOO_MOSAIC,
        Material.BAMBOO_PLANKS,
        Material.BAMBOO_PRESSURE_PLATE,
        Material.BAMBOO_RAFT,
        Material.BAMBOO_SIGN,
        Material.BAMBOO_SLAB,
        Material.BAMBOO_STAIRS,
        Material.BAMBOO_TRAPDOOR,
        // Material.BAMBOO_WALL_HANGING_SIGN,
        Material.BAMBOO_WALL_SIGN,
        Material.BIRCH_HANGING_SIGN,
        // Material.BIRCH_WALL_HANGING_SIGN,
        Material.BLADE_POTTERY_SHERD,
        Material.BREWER_POTTERY_SHERD,
        Material.BRUSH,
        Material.BURN_POTTERY_SHERD,
        //Material.CALIBRATED_SCULK_SENSOR,
        Material.CHERRY_BOAT,
        Material.CHERRY_BUTTON,
        Material.CHERRY_CHEST_BOAT,
        Material.CHERRY_DOOR,
        Material.CHERRY_FENCE_GATE,
        Material.CHERRY_FENCE,
        Material.CHERRY_HANGING_SIGN,
        Material.CHERRY_LEAVES,
        Material.CHERRY_LOG,
        Material.CHERRY_PLANKS,
        Material.CHERRY_PRESSURE_PLATE,
        Material.CHERRY_SAPLING,
        Material.CHERRY_SIGN,
        Material.CHERRY_SLAB,
        Material.CHERRY_STAIRS,
        Material.CHERRY_TRAPDOOR,
        // Material.CHERRY_WALL_HANGING_SIGN,
        Material.CHERRY_WALL_SIGN,
        Material.CHERRY_WOOD,
        Material.CHISELED_BOOKSHELF,
        Material.COAST_ARMOR_TRIM_SMITHING_TEMPLATE,
        Material.DANGER_POTTERY_SHERD,
        Material.DARK_OAK_HANGING_SIGN,
        // Material.DARK_OAK_WALL_HANGING_SIGN,
        // Material.DECORATED_POT,
        Material.DIORITE_SLAB,
        Material.DUNE_ARMOR_TRIM_SMITHING_TEMPLATE,
        Material.EXPLORER_POTTERY_SHERD,
        Material.EYE_ARMOR_TRIM_SMITHING_TEMPLATE,
        Material.FRIEND_POTTERY_SHERD,
        Material.HEART_POTTERY_SHERD,
        Material.HEARTBREAK_POTTERY_SHERD,
        Material.HOST_ARMOR_TRIM_SMITHING_TEMPLATE,
        Material.HOWL_POTTERY_SHERD,
        Material.JUNGLE_HANGING_SIGN,
        // Material.JUNGLE_WALL_HANGING_SIGN,
        Material.MANGROVE_BUTTON,
        Material.MANGROVE_HANGING_SIGN,
        // Material.MANGROVE_WALL_HANGING_SIGN,
        Material.MINER_POTTERY_SHERD,
        Material.MOURNER_POTTERY_SHERD,
        Material.MUSIC_DISC_RELIC,
        Material.OAK_HANGING_SIGN,
        // Material.OAK_WALL_HANGING_SIGN,
        Material.PINK_PETALS,
//        Material.PITCHER_CROP,
        // Material.PITCHER_PLANT,
        Material.PITCHER_POD,
        Material.PLENTY_POTTERY_SHERD,
        // Material.POTTED_CHERRY_SAPLING,
        // Material.POTTED_TORCHFLOWER,
        Material.PRIZE_POTTERY_SHERD,
        Material.RAISER_ARMOR_TRIM_SMITHING_TEMPLATE,
        Material.RIB_ARMOR_TRIM_SMITHING_TEMPLATE,
        Material.SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE,
        Material.SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE,
        Material.SHEAF_POTTERY_SHERD,
        Material.SHELTER_POTTERY_SHERD,
        Material.SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE,
        Material.SKULL_POTTERY_SHERD,
        Material.SNIFFER_EGG,
        Material.SNORT_POTTERY_SHERD,
        Material.SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE,
        Material.SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE,
        Material.SPRUCE_HANGING_SIGN,
        // Material.SPRUCE_WALL_HANGING_SIGN,
        Material.STRIPPED_BAMBOO_BLOCK,
        Material.STRIPPED_CHERRY_LOG,
        Material.STRIPPED_CHERRY_WOOD,
        // Material.SUSPICIOUS_GRAVEL,
        // Material.SUSPICIOUS_SAND,
        Material.TIDE_ARMOR_TRIM_SMITHING_TEMPLATE,
        // Material.TORCHFLOWER_CROP,
        Material.TORCHFLOWER_SEEDS,
        Material.TORCHFLOWER,
        Material.VEX_ARMOR_TRIM_SMITHING_TEMPLATE,
        Material.WARD_ARMOR_TRIM_SMITHING_TEMPLATE,
        Material.WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE,
        Material.WILD_ARMOR_TRIM_SMITHING_TEMPLATE
    );

    public static List<Material> netherPrizes = (List<Material>)Arrays.asList(
        Material.ANCIENT_DEBRIS,
        Material.BASALT,
        Material.BEACON,
        Material.BLACKSTONE,
        Material.BLAZE_POWDER,
        Material.BLAZE_ROD,
        Material.BREWING_STAND,
        Material.CHAIN,
        Material.CHISELED_NETHER_BRICKS,
        Material.CHISELED_POLISHED_BLACKSTONE,
        Material.COMPARATOR,
        Material.CRACKED_NETHER_BRICKS,
        Material.CRACKED_POLISHED_BLACKSTONE_BRICKS,
        Material.CRIMSON_HYPHAE,
        Material.CRIMSON_NYLIUM,
        Material.CRIMSON_STEM,
        Material.CRIMSON_TRAPDOOR,
        Material.CRIMSON_WALL_SIGN,
        Material.CRYING_OBSIDIAN,
        Material.DAYLIGHT_DETECTOR,
        Material.ENDER_CHEST,
        Material.ENDER_EYE,
        Material.GHAST_TEAR,
        Material.GILDED_BLACKSTONE,
        Material.GLOWSTONE,
        Material.LODESTONE,
        Material.MAGMA_BLOCK,
        Material.MAGMA_CREAM,
        Material.MUSIC_DISC_PIGSTEP,
        Material.NETHERITE_AXE,
        Material.NETHERITE_BLOCK,
        Material.NETHERITE_INGOT,
        Material.NETHER_BRICK_FENCE,
        Material.NETHER_BRICK_SLAB,
        Material.NETHER_BRICK_STAIRS,
        Material.NETHER_BRICK,
        Material.NETHER_BRICKS,
        Material.NETHER_GOLD_ORE,
        Material.NETHER_QUARTZ_ORE,
        Material.NETHER_SPROUTS,
        Material.NETHER_STAR,
        Material.NETHER_WART_BLOCK,
        Material.NETHER_WART,
        Material.QUARTZ_BLOCK,
        Material.QUARTZ_BRICKS,
        Material.QUARTZ_PILLAR,
        Material.QUARTZ_SLAB,
        Material.QUARTZ_STAIRS,
        Material.QUARTZ,
        Material.RED_NETHER_BRICKS,
        Material.RESPAWN_ANCHOR,
        Material.SHROOMLIGHT,
        Material.SMOOTH_QUARTZ,
        Material.SOUL_CAMPFIRE,
        Material.SOUL_LANTERN,
        Material.SOUL_SAND,
        Material.SOUL_SOIL,
        Material.SOUL_TORCH,
        Material.TARGET,
        Material.TWISTING_VINES,
        Material.TWISTING_VINES_PLANT,
        Material.WARPED_HYPHAE,
        Material.WARPED_NYLIUM,
        Material.WARPED_STEM,
        Material.WEEPING_VINES,
        Material.WITHER_SKELETON_SKULL,
        // 1.20
        Material.CRIMSON_HANGING_SIGN,
        // Material.CRIMSON_WALL_HANGING_SIGN,
        Material.NETHERITE_UPGRADE_SMITHING_TEMPLATE,
        Material.WARPED_HANGING_SIGN
        // Material.WARPED_WALL_HANGING_SIGN

    );

    public static List<Material> endPrizes = (List<Material>)Arrays.asList(
        Material.BLACK_SHULKER_BOX,
        Material.BLUE_SHULKER_BOX,
        Material.BROWN_SHULKER_BOX,
        Material.CHORUS_FLOWER,
        Material.CHORUS_FRUIT,
        Material.CHORUS_PLANT,
        Material.CYAN_SHULKER_BOX,
        Material.DRAGON_HEAD,
        Material.ELYTRA,
        Material.END_CRYSTAL,
        Material.END_ROD,
        Material.GRAY_SHULKER_BOX,
        Material.GREEN_SHULKER_BOX,
        Material.LIGHT_BLUE_SHULKER_BOX,
        Material.LIME_SHULKER_BOX,
        Material.MAGENTA_SHULKER_BOX,
        Material.ORANGE_SHULKER_BOX,
        Material.PINK_SHULKER_BOX,
        Material.POPPED_CHORUS_FRUIT,
        Material.PURPLE_SHULKER_BOX,
        Material.PURPUR_BLOCK,
        Material.PURPUR_PILLAR,
        Material.PURPUR_SLAB,
        Material.PURPUR_STAIRS,
        Material.RED_SHULKER_BOX,
        Material.SHULKER_BOX,
        Material.SHULKER_SHELL,
        Material.WHITE_SHULKER_BOX,
        Material.YELLOW_SHULKER_BOX,
        Material.LIGHT_GRAY_SHULKER_BOX
    );

    public static List<Material> overworldEnchantableList = (List<Material>)Arrays.asList(
        Material.ARROW,
        Material.BOW,
        Material.CHAINMAIL_BOOTS,
        Material.CHAINMAIL_CHESTPLATE,
        Material.CHAINMAIL_HELMET,
        Material.CHAINMAIL_LEGGINGS,
        Material.DIAMOND_AXE,
        Material.DIAMOND_BOOTS,
        Material.DIAMOND_CHESTPLATE,
        Material.DIAMOND_HELMET,
        Material.DIAMOND_HOE,
        Material.DIAMOND_LEGGINGS,
        Material.DIAMOND_PICKAXE,
        Material.DIAMOND_SHOVEL,
        Material.DIAMOND_SWORD,
        Material.FISHING_ROD,
        Material.FLINT_AND_STEEL,
        Material.GOLDEN_AXE,
        Material.GOLDEN_BOOTS,
        Material.GOLDEN_CHESTPLATE,
        Material.GOLDEN_HOE,
        Material.GOLDEN_LEGGINGS,
        Material.GOLDEN_PICKAXE,
        Material.GOLDEN_SHOVEL,
        Material.GOLDEN_SWORD,
        Material.IRON_AXE,
        Material.IRON_BOOTS,
        Material.IRON_CHESTPLATE,
        Material.IRON_HELMET,
        Material.IRON_HOE,
        Material.IRON_LEGGINGS,
        Material.IRON_PICKAXE,
        Material.IRON_SHOVEL,
        Material.IRON_SWORD,
        Material.SHIELD,
        Material.SHEARS,
        Material.TRIDENT
    );

    public static List<Material> netherEnchantableList = (List<Material>)Arrays.asList(
        Material.NETHERITE_BOOTS,
        Material.NETHERITE_SCRAP,
        Material.NETHERITE_CHESTPLATE,
        Material.NETHERITE_HELMET,
        Material.NETHERITE_HOE,
        Material.NETHERITE_LEGGINGS,
        Material.NETHERITE_PICKAXE,
        Material.NETHERITE_SHOVEL,
        Material.NETHERITE_SWORD
    );

    public static Map<Material, Integer> prizeLimits = new HashMap<Material, Integer>();

    public static void setPrizeLimits() {
        prizeLimits.put(Material.ENCHANTED_GOLDEN_APPLE, 5);
        prizeLimits.put(Material.NETHER_STAR, 3);
        prizeLimits.put(Material.BEACON, 3);
        prizeLimits.put(Material.END_CRYSTAL, 3);
        prizeLimits.put(Material.CREEPER_HEAD, 5);
        prizeLimits.put(Material.PLAYER_HEAD, 5);
        prizeLimits.put(Material.SKELETON_SKULL, 5);
        prizeLimits.put(Material.WITHER_SKELETON_SKULL, 5);
        prizeLimits.put(Material.ZOMBIE_HEAD, 5);
        prizeLimits.put(Material.IRON_BLOCK, 32);
        prizeLimits.put(Material.GOLD_BLOCK, 16);
        prizeLimits.put(Material.DIAMOND_BLOCK, 8);
        prizeLimits.put(Material.EMERALD_BLOCK, 8);
        prizeLimits.put(Material.DIAMOND, 32);
        prizeLimits.put(Material.DIAMOND_ORE, 16);
        prizeLimits.put(Material.GOLDEN_APPLE, 5);
        prizeLimits.put(Material.ENDER_CHEST, 8);
        prizeLimits.put(Material.GHAST_TEAR, 8);
        prizeLimits.put(Material.AIR, 1);
        prizeLimits.put(Material.PHANTOM_MEMBRANE, 10);
        prizeLimits.put(Material.CONDUIT, 3);
        prizeLimits.put(Material.NAUTILUS_SHELL, 10);
        prizeLimits.put(Material.HEART_OF_THE_SEA, 3);
        prizeLimits.put(Material.NETHERITE_SCRAP, 32);
        prizeLimits.put(Material.NETHERITE_INGOT, 10);
        prizeLimits.put(Material.NETHERITE_BLOCK, 1);
        prizeLimits.put(Material.SHULKER_SHELL, 8);
        prizeLimits.put(Material.DRAGON_HEAD, 3);
        prizeLimits.put(Material.COAST_ARMOR_TRIM_SMITHING_TEMPLATE,1);
        prizeLimits.put(Material.DUNE_ARMOR_TRIM_SMITHING_TEMPLATE,1);
        prizeLimits.put(Material.EYE_ARMOR_TRIM_SMITHING_TEMPLATE,1);
        prizeLimits.put(Material.HOST_ARMOR_TRIM_SMITHING_TEMPLATE,1);
        prizeLimits.put(Material.NETHERITE_UPGRADE_SMITHING_TEMPLATE,1);
        prizeLimits.put(Material.RAISER_ARMOR_TRIM_SMITHING_TEMPLATE,1);
        prizeLimits.put(Material.RIB_ARMOR_TRIM_SMITHING_TEMPLATE,1);
        prizeLimits.put(Material.SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE,1);
        prizeLimits.put(Material.SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE,1);
        prizeLimits.put(Material.SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE,1);
        prizeLimits.put(Material.SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE,1);
        prizeLimits.put(Material.SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE,1);
        prizeLimits.put(Material.TIDE_ARMOR_TRIM_SMITHING_TEMPLATE,1);
        prizeLimits.put(Material.VEX_ARMOR_TRIM_SMITHING_TEMPLATE,1);
        prizeLimits.put(Material.WARD_ARMOR_TRIM_SMITHING_TEMPLATE,1);
        prizeLimits.put(Material.WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE,1);
        prizeLimits.put(Material.WILD_ARMOR_TRIM_SMITHING_TEMPLATE,1);
        prizeLimits.put(Material.NETHERITE_UPGRADE_SMITHING_TEMPLATE,1);

    }
}
